spring.application.name=scheduler

# Server
server.port=1234

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/schedulerflow
spring.datasource.username=schedulerflow
spring.datasource.password=dev
spring.datasource.driver-class-name=org.postgresql.Driver

# JOOQ
spring.sql.init.mode=always

# Logging
logging.level.root=INFO
logging.level.com.schd.scheduler=DEBUG
logging.level.org.jooq=DEBUG

# HATEOAS
# spring.hateoas.use-hal-as-default-json-media-type=true